### PR TITLE
Simplify block generation

### LINKED ISSUE #70: Add checking for a valid JSON to the svzerodsolver application
The `svzerodsolver` application does not appear to check if the input JSON file contains valid information. 

For example running `svzerodsolver`  with `steadyFlow_calibration.json` produces the confusing error message
```
libc++abi.dylib: terminating with uncaught exception of type nlohmann::json_abi_v3_11_2::detail::type_error: [json.exception.type_error.306] cannot use value() with number
```
I spent a good amount of time trying to figure out the cause of this error, thought the JSON file was corrupted or something.

Other examples 
- removing the `junctions` JSON element produces a segfault
- adding another `"boundary_conditions` JSON element produces a segfault
- removing the `vessels` JSON element produces `cannot use operator[] with a numeric argument with number`

We will need to add some checks in the solver code to identify these errors and throw an exception with a helpful message.

### PR DESCRIPTION
**Pull request by mrp089**
## Current situation
Closes #70 and #71: Simplifies block generation and introduces more error checking.

## Release Notes
Major structure:
- `Model.cpp`: `block_factory_map` replaces `switch case` statement to generate new blocks
- Introduced `InputParameter` struct to store properties of input parameters (name, array?, optional?, number?, default value)
- Set `InputParameter`, `BlockType` (e.g. `blood_vessel`), and `BlockClass` (e.g. `closed_loop`) in the constructor of all derived `Block` classes

Major in `solve/SimulationParameters.cpp` (the file formerly known as `io/configreader.hpp`):
- Functions `get_param_scalar` and `get_param_vector` return an error if the input parameter is not optional and doesn't exist
- New universal `generate_block` function to create a block, read its input parameters, and register block and parameters with `Model`
- Replaced all block-specific parameter setups with `generate_block`
- Broke `load_simulation_params` up into sub-functions and introduced more input-checking:
    - `create_vessels`
    - `create_coupling`
    - `create_bounary_conditions`
    - `create_junctions`
    - `create_closed_loop`

New error checks:
- Cases documented in #70 
- Are all (non-optional) input parameters for each block given?
- Are any unknown input parameters given?

Minor:
- Doxygen: Set `WARN_AS_ERROR`  to `FAIL_ON_WARNINGS`. This runs the whole build and throws all warnings as errors. (`YES` fails after the first error, which is annoying for debugging).
- Split up `ClosedLoopCoronaryBC` into `ClosedLoopCoronaryLeftBC` and `ClosedLoopCoronaryRightBC` (replaces `side` input parameter)

Limitations:
- There are still places in `SimulationParameters.cpp` that are very block-specific (especially in `create_coupling`). These could be replaced in the future by using `BlockType`, `BlockClass`, or new `Block` attributes.
- Add/move more error checks to `validate_input`.

## Documentation
I updated the Doxygen documentation. After merging this, we can create a section on creating new blocks in the developer guide (#66).

## Testing
We have built ourselves a very nice `CI` framework! I worked myself through all the block and interface tests. I made the following changes to the input files:
- Removed empty `vessels` and `junctions` inputs as they are no longer required
- Removed `side` input parameter and renamed `ClosedLoopCoronary` blocks
- Removed unused input (`unsteady` in `ClosedLoopRCR`, `ClosedLoopCoronary` and `C` in `BloodVesselJunction`)

## Code of Conduct & Contributing Guidelines 
- [x] I agree to follow the [Code of Conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mrp089** [comment]
I added more input checks after talking to @richterjakob and edited the first comment accordingly.

File: src/model/Model.cpp [hunk 1]
```diff
@@ -30,82 +30,51 @@
...
-    case BlockType::closed_loop_heart_pulmonary:
-      block = new ClosedLoopHeartPulmonary(block_count, block_param_ids, this);
-      break;
-
-    default:
-      throw std::runtime_error(
-          "Adding block to model failed: Invalid block type!");
+Block *Model::create_block(const std::string &block_name) {
+  // Get block from factory
+  auto it = block_factory_map.find(block_name);
```
Comment (menon-karthik) [inline src/model/Model.cpp:66]: Should `block_name` be called `block_type` for clarity?

File: src/solve/SimulationParameters.cpp [hunk 2]
```diff
@@ -32,35 +32,143 @@
...
+  return false;
 }
 
-std::vector<double> get_double_array(const nlohmann::json& data,
-                                     const std::string_view& key,
-                                     const std::vector<double>& default_value) {
-  if (!data.contains(key)) {
-    return default_value;
+int generate_block(Model& model, const nlohmann::json& config,
+                   const std::string& block_name, const std::string_view& name,
```
Comment (menon-karthik) [inline src/solve/SimulationParameters.cpp:75]: Should `block_name` be named `block_type` instead?

File: src/solve/SimulationParameters.cpp [hunk 3]
```diff
@@ -90,44 +198,74 @@ SimulationParameters load_simulation_params(const nlohmann::json& config) {
...
+  std::map<std::string, std::string> bc_type_map;
+  for (const auto& bc_config : config["boundary_conditions"]) {
+    std::string bc_name = bc_config["bc_name"];
+    std::string bc_type = bc_config["bc_type"];
+    bc_type_map.insert({bc_name, bc_type});
+  }
+
+  // Create external coupling blocks
+  if (config.contains("external_solver_coupling_blocks")) {
+    create_coupling(model, connections,
```
Comment (menon-karthik) [inline src/solve/SimulationParameters.cpp:224]: I would call this `create_external_coupling` to distinguish between this and coupling/connection nodes within the 0D model.

File: src/solve/SimulationParameters.cpp [hunk 4]
```diff
@@ -90,44 +198,74 @@ SimulationParameters load_simulation_params(const nlohmann::json& config) {
...
+                    config["external_solver_coupling_blocks"], vessel_id_map,
+                    bc_type_map);
+  }
+
+  // Create boundary conditions
+  std::vector<std::string> closed_loop_bcs;
+  create_bounary_conditions(model, config["boundary_conditions"], bc_type_map,
```
Comment (menon-karthik) [inline src/solve/SimulationParameters.cpp:231]: Typo.

File: tests/test_interface/test_01/svzerod_3Dcoupling.json [hunk 5]
```diff
@@ -13,272 +13,249 @@
...
         {
             "bc_name": "BC_lca1",
-            "bc_type": "ClosedLoopCoronary",
+            "bc_type": "ClosedLoopCoronaryLeft",
             "bc_values": {
                 "Ra": 145.27234317,
                 "Ram": 236.06755765,
                 "Rv": 290.06461147,
                 "Cim": 0.00105039,
-                "Ca": 0.00010326,
```
Comment (menon-karthik) [inline tests/test_interface/test_01/svzerod_3Dcoupling.json:28]: Why did you remove `Ca`?

File: tests/test_interface/test_02/svzerod_tuned.json [hunk 6]
```diff
@@ -14,272 +14,249 @@
...
         {
             "bc_name": "BC_lca1",
-            "bc_type": "ClosedLoopCoronary",
+            "bc_type": "ClosedLoopCoronaryLeft",
             "bc_values": {
                 "Ra": 145.27234317,
                 "Ram": 236.06755765,
                 "Rv": 290.06461147,
                 "Cim": 0.00105039,
-                "Ca": 0.00010326,
```
Comment (menon-karthik) [inline tests/test_interface/test_02/svzerod_tuned.json:29]: Same comment here about `Ca`.

File: src/solve/SimulationParameters.cpp [hunk 7]
```diff
@@ -90,44 +198,74 @@ SimulationParameters load_simulation_params(const nlohmann::json& config) {
...
-                       model.add_parameter(vessel_values.value("C", 0.0)),
-                       model.add_parameter(vessel_values.value("L", 0.0)),
-                       model.add_parameter(
-                           vessel_values.value("stenosis_coefficient", 0.0))},
-                      vessel_name);
-      // DEBUG_MSG("Created vessel " << vessel_name);
-    } else {
-      throw std::invalid_argument("Unknown vessel type");
-    }
+    generate_block(model, vessel_values, vessel_config["zero_d_element_type"],
```
Comment (menon-karthik) [inline src/solve/SimulationParameters.cpp:267]: I'm confused that this call doesn't match the arguments in `generate_block` and I don't see an overloaded function that matches this call. Specifically, the second and third arguments here are the same (`vessel_values = vessel_config["zero_d_element_values"]`). But the second argument should be a json config and the third should be a string. Am I missing something?

**Review by menon-karthik — CHANGES_REQUESTED** [review]
This looks really good @mrp089. Thanks for this much-needed work! I have a few minor comments.

File: src/solve/SimulationParameters.cpp (hunk 2 above)
Comment (mrp089) [reply src/solve/SimulationParameters.cpp:75]: Yes!

File: src/solve/SimulationParameters.cpp (hunk 4 above)
Comment (mrp089) [reply src/solve/SimulationParameters.cpp:231]: Fixed!

File: tests/test_interface/test_02/svzerod_tuned.json (hunk 6 above)
Comment (mrp089) [reply tests/test_interface/test_02/svzerod_tuned.json:29]: As above

File: src/solve/SimulationParameters.cpp (hunk 7 above)
Comment (mrp089) [reply src/solve/SimulationParameters.cpp:267]: Argument two `vessel_values = vessel_config["zero_d_element_values"]` contains the `nlohmann::json` "sub-json" configuration of this block (e.g., `{C: 0.001, L: 0.01}`).
Argument three `vessel_config["zero_d_element_type"]` contains only the `std::string` type of the vessel (e.g., `BloodVessel`).

The confusion is probably that both arguments are extracted from the `json` configuration of this block. However, it does require two separate arguments since they look different in each of the `create_[...]` functions:
- `create_vessels`: `zero_d_element_values` and `zero_d_element_type`
- `create_boundary_conditions`: `bc_values` and `bc_type`
- `create_external_coupling`: `values` and `name`
- `create_junctions`: `junction_values` and `junction_type`
- ...

Maybe we could unify that in the future by changing our input files?

Comment (menon-karthik) [reply src/solve/SimulationParameters.cpp:267]: Ah ok, sorry I accidentally read the third argument as `zero_d_element_values` instead of `zero_d_element_type`. Makes sense now!

**Review by menon-karthik — APPROVED** [review]
