### PR TITLE
More input checks

### LINKED ISSUE #70: Add checking for a valid JSON to the svzerodsolver application
The `svzerodsolver` application does not appear to check if the input JSON file contains valid information. 

For example running `svzerodsolver`  with `steadyFlow_calibration.json` produces the confusing error message
```
libc++abi.dylib: terminating with uncaught exception of type nlohmann::json_abi_v3_11_2::detail::type_error: [json.exception.type_error.306] cannot use value() with number
```
I spent a good amount of time trying to figure out the cause of this error, thought the JSON file was corrupted or something.

Other examples 
- removing the `junctions` JSON element produces a segfault
- adding another `"boundary_conditions` JSON element produces a segfault
- removing the `vessels` JSON element produces `cannot use operator[] with a numeric argument with number`

We will need to add some checks in the solver code to identify these errors and throw an exception with a helpful message.

### PR DESCRIPTION
**Pull request by mrp089**
## Current situation
Closes #70

## Release Notes 
I added two new features for error checking:
1. JsonWrapper class
    - wrapper around `nlohmann::json`
    - overwrite `[]` operator that will throw a detailed error where an input parameter is missing
    - used by all `create_...` functions in `SimulationParameters`
    - should catch all errors where required components are not given (e.g. due to spelling)
2. Throw an error in `Model::get_block` if the block name doesn't exist
    - checks if block exists in `Model::has_block`
    - deleted `get_block` error handling in `interface` as it's not necessary anymore
    - replaced comparisons with `nullptr` by calling `has_block`
    - should catch all errors where non-existing block names are used anywhere in the input file

## Documentation
Added required Doxygen documentation to new code

## Testing
Verified that the examples in #70 and other random manipulations of test cases throw a descriptive error message

## Code of Conduct & Contributing Guidelines 
- [x] I agree to follow the [Code of Conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: src/solve/SimulationParameters.h [hunk 1]
```diff
@@ -74,6 +74,47 @@ struct SimulationParameters {
...
+   * doesn't exist)
+   *
+   * @param key Key to retrieve from JSON object
+   * @return JSON entry of key
+   */
+  const nlohmann::json& operator[](const char* key) const {
+    if (!this->contains(key)) {
+      throw std::runtime_error(
+          "Key " + std::string(key) + " not found in element number " +
+          std::to_string(block_id) + " of component " + component);
```
Comment (menon-karthik) [inline src/solve/SimulationParameters.h:103]: Is there a way to throw an error with the name of the element instead of the ID? For example, if you have a JSON file with 100 boundary conditions and there is a type in the 73rd one, it might be hard to find the error with only the index. Not a big deal if that is too hard to implement.

File: src/solve/SimulationParameters.cpp
Comment (menon-karthik) [inline src/solve/SimulationParameters.cpp:1]: Only sort of related to the current pull request (in the context of error checking): Wouldn't it make more sense for `get_param_scalar` and `get_param_vector` to return `false` when they fail and `true` otherwise? It was confusing to me but I forgot to mention it in the original pull request.

File: src/solve/SimulationParameters.h (hunk 1 above)
Comment (menon-karthik) [inline src/solve/SimulationParameters.h:103]: Is there a way to throw an error with the name of the element instead of the ID? For example, if you have a JSON file with 100 boundary conditions and there is a type in the 73rd one, it might be hard to find the error with only the index. Not a big deal if that is too hard to implement.

**Review by menon-karthik — CHANGES_REQUESTED** [review]
This is really useful and should address both the problems @ktbolt mentioned in [here](https://github.com/StanfordCBCL/svZeroDPlus/issues/70#issuecomment-1839455076) in #70 . Thanks @mrp089! I have two (hopefully) minor comments.

File: src/solve/SimulationParameters.cpp
Comment (menon-karthik) [reply src/solve/SimulationParameters.cpp:1]: To me, the reason it is confusing is because of this usage [here](https://github.com/StanfordCBCL/svZeroDPlus/blob/ca4c4bdf811b4968b8161186dcc1ec23c16ef2b8/src/solve/SimulationParameters.cpp#L123). For this specific case, I think a true/false return makes more sense and is more concise than an exit code.

File: src/solve/SimulationParameters.h (hunk 1 above)
Comment (mrp089) [reply src/solve/SimulationParameters.h:103]: It can definitely be done. The caveat is that the name could be corrupted (missing or wrong key), so we'd have to check for that before initializing `JsonWrapper` or in its constructor. 

I just noticed that we have different name keys for different categories (`vessel_name, bc_name, junction_name, name`), and `ClosedLoopHeartAndPulmonary` doesn't have a name - Same thing for `type`.

Both make reading out the name in the error message a bit tedious. Up to you if we want to include it!

Comment (menon-karthik) [reply src/solve/SimulationParameters.h:103]: Yeah I guess the easiest way would be to have a `if (!config[component].contains(<name-key>)) {throw error}` before each `JsonWrapper` is initialized (except `ClosedLoopHeartAndPulmonary`). I'm fine with leaving it as is or adding this condition.

File: src/solve/SimulationParameters.cpp
Comment (mrp089) [reply src/solve/SimulationParameters.cpp:1]: Ah, I see. Would something like
```.cpp
int err = get_param_vector(...)
if (err) { ...}
```
be better?

**Review by menon-karthik — APPROVED** [review]
Look great, thanks again @mrp089 !
